name: Deploy Backend to Ubuntu Server

on:
  push:
    branches: [ master ]
    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Configuring git credentials..."
            cd /home/${{ secrets.SERVER_USERNAME }}/PingMeChat
            git config --global credential.helper store
            echo "https://${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
            
            echo "Pulling new code..."
            git fetch origin master
            git reset --hard origin/master
            
            echo "Building and restarting API service..."
            cd Backend
            
            # Build và restart chỉ service API
            docker-compose stop pingmechat-cms-api
            docker-compose rm -f pingmechat-cms-api
            docker-compose build pingmechat-cms-api
            docker-compose up -d pingmechat-cms-api
            
            # Cleanup
            docker image prune -f
            
            # Check logs
            echo "Deployment completed. Checking logs..."
            docker-compose logs --tail=20 pingmechat-cms-api
            
            # Check container status
            echo "Container status:"
            docker ps
            
            # Cleanup git credentials
            rm ~/.git-credentials
